export const LAYOUT = {
  SIDEBAR_EXPANDED_WIDTH: 220,
  SIDEBAR_COLLAPSED_WIDTH: 52,
  CONTEXT_PANEL_WIDTH: 300,
  CONTENT_MIN_WIDTH: 560,
  CONTENT_MAX_READING_WIDTH: 880,
  CONTENT_INNER_PADDING: 24,
} as const
