import type { DashboardArea, DashboardNote, DashboardInboxItem } from './types'

export const paraBuckets: DashboardArea[] = [
  { id: '1', name: 'Perp Exchange Book', type: 'project', note_count: 34, last_capture_at: '2026-02-17', health: 'growing', children: [] },
  { id: '2', name: 'Watch Research', type: 'project', note_count: 12, last_capture_at: '2026-01-28', health: 'stable', children: [] },
  { id: '3', name: 'Second Brain Build', type: 'project', note_count: 8, last_capture_at: '2026-02-18', health: 'growing', children: [] },
  { id: '4', name: 'DeFi', type: 'area', note_count: 147, last_capture_at: '2026-02-16', health: 'growing', children: [] },
  { id: '5', name: 'Cars', type: 'area', note_count: 43, last_capture_at: '2026-02-10', health: 'growing', children: [] },
  { id: '6', name: 'Design', type: 'area', note_count: 22, last_capture_at: '2025-12-05', health: 'stagnant', children: [] },
  { id: '7', name: 'LA', type: 'area', note_count: 15, last_capture_at: '2026-02-14', health: 'growing', children: [] },
  { id: '8', name: 'Watches', type: 'area', note_count: 56, last_capture_at: '2026-02-08', health: 'growing', children: [] },
  { id: '9', name: 'Finance', type: 'area', note_count: 31, last_capture_at: '2026-02-12', health: 'growing', children: [] },
  { id: '10', name: 'Social', type: 'area', note_count: 9, last_capture_at: '2026-01-20', health: 'stable', children: [] },
]

export const recentNotes: DashboardNote[] = [
  {
    id: 'n1',
    title: "Hyperliquid's 200K Orders/Sec Architecture",
    ai_summary: 'Lock-free data structures enable parallel order matching across non-overlapping price levels.',
    distillation: null,
    source_type: 'article',
    source: { domain: 'hyperliquid.xyz' },
    distillation_status: 'distilled',
    bucket_id: '4',
    bucket_path: 'Areas/DeFi',
    captured_at: '2026-02-16',
    connection_count: 8,
  },
  {
    id: 'n2',
    title: 'Funding Rate Arbitrage Between CEX and DEX',
    ai_summary: 'The spread between Binance and Hyperliquid funding rates creates a persistent arb opportunity.',
    distillation: null,
    source_type: 'tweet',
    source: { domain: 'x.com' },
    distillation_status: 'key_points',
    bucket_id: '4',
    bucket_path: 'Areas/DeFi',
    captured_at: '2026-02-15',
    connection_count: 4,
  },
  {
    id: 'n3',
    title: 'E30 M3 Engine Swap Options',
    ai_summary: 'S50B32 is the most popular swap. Requires custom motor mounts and ECU remapping.',
    distillation: null,
    source_type: 'article',
    source: { domain: 'bimmerforums.com' },
    distillation_status: 'raw',
    bucket_id: '5',
    bucket_path: 'Areas/Cars',
    captured_at: '2026-02-14',
    connection_count: 2,
  },
  {
    id: 'n4',
    title: 'Dieter Rams: Less But Better',
    ai_summary: 'Good design is as little design as possible. Back to purity, back to simplicity.',
    distillation: null,
    source_type: 'pdf',
    source: {},
    distillation_status: 'evergreen',
    bucket_id: '6',
    bucket_path: 'Areas/Design',
    captured_at: '2025-11-20',
    connection_count: 12,
  },
  {
    id: 'n5',
    title: 'On-chain Orderbook Tradeoffs',
    ai_summary: 'Matching on-chain gives transparency but throughput is bottlenecked by block time.',
    distillation: null,
    source_type: 'thought',
    source: {},
    distillation_status: 'distilled',
    bucket_id: '4',
    bucket_path: 'Areas/DeFi',
    captured_at: '2026-02-13',
    connection_count: 6,
  },
  {
    id: 'n6',
    title: 'Patek Philippe Nautilus History',
    ai_summary: 'Designed by Gerald Genta in 1976. The porthole case shape was inspired by transatlantic ships.',
    distillation: null,
    source_type: 'article',
    source: { domain: 'hodinkee.com' },
    distillation_status: 'key_points',
    bucket_id: '8',
    bucket_path: 'Areas/Watches',
    captured_at: '2026-02-08',
    connection_count: 3,
  },
]

export const inboxItems: DashboardInboxItem[] = [
  {
    id: 'i1',
    title: 'Thread: MEV on Hyperliquid L1',
    ai_summary: "Detailed analysis of how MEV extraction works on Hyperliquid's custom L1 vs Ethereum.",
    source_type: 'tweet',
    source: { domain: 'x.com' },
    ai_suggested_bucket: null,
    ai_suggested_bucket_path: 'Areas/DeFi',
    captured_at: '2026-02-18',
  },
  {
    id: 'i2',
    title: 'Best Restaurants in Silver Lake',
    ai_summary: 'Curated list of top-rated restaurants in the Silver Lake neighborhood of LA.',
    source_type: 'article',
    source: {},
    ai_suggested_bucket: null,
    ai_suggested_bucket_path: 'Areas/LA',
    captured_at: '2026-02-18',
  },
  {
    id: 'i3',
    title: 'Voice Memo: Idea for Order Routing',
    ai_summary: 'Thought about smart order routing across multiple DEX venues based on depth.',
    source_type: 'voice_memo',
    source: {},
    ai_suggested_bucket: null,
    ai_suggested_bucket_path: 'Projects/Perp Exchange Book',
    captured_at: '2026-02-17',
  },
  {
    id: 'i4',
    title: 'A. Lange & Sohne Datograph Review',
    ai_summary: 'Comprehensive review of the Datograph Up/Down. Considered one of the best chronographs ever made.',
    source_type: 'article',
    source: {},
    ai_suggested_bucket: null,
    ai_suggested_bucket_path: 'Areas/Watches',
    captured_at: '2026-02-17',
  },
  {
    id: 'i5',
    title: 'React Server Components Deep Dive',
    ai_summary: 'Explains how RSC reduces client-side JS by rendering components on the server.',
    source_type: 'article',
    source: {},
    ai_suggested_bucket: null,
    ai_suggested_bucket_path: 'Resources',
    captured_at: '2026-02-16',
  },
]
