import type { ParaBucket, Note, InboxItem } from './types'

export const paraBuckets: ParaBucket[] = [
  { id: '1', name: 'Perp Exchange Book', type: 'project', noteCount: 34, lastCaptureDate: '2026-02-17' },
  { id: '2', name: 'Watch Research', type: 'project', noteCount: 12, lastCaptureDate: '2026-01-28' },
  { id: '3', name: 'Second Brain Build', type: 'project', noteCount: 8, lastCaptureDate: '2026-02-18' },
  { id: '4', name: 'DeFi', type: 'area', noteCount: 147, lastCaptureDate: '2026-02-16' },
  { id: '5', name: 'Cars', type: 'area', noteCount: 43, lastCaptureDate: '2026-02-10' },
  { id: '6', name: 'Design', type: 'area', noteCount: 22, lastCaptureDate: '2025-12-05' },
  { id: '7', name: 'LA', type: 'area', noteCount: 15, lastCaptureDate: '2026-02-14' },
  { id: '8', name: 'Watches', type: 'area', noteCount: 56, lastCaptureDate: '2026-02-08' },
  { id: '9', name: 'Finance', type: 'area', noteCount: 31, lastCaptureDate: '2026-02-12' },
  { id: '10', name: 'Social', type: 'area', noteCount: 9, lastCaptureDate: '2026-01-20' },
]

export const recentNotes: Note[] = [
  {
    id: 'n1',
    title: "Hyperliquid's 200K Orders/Sec Architecture",
    excerpt: 'Lock-free data structures enable parallel order matching across non-overlapping price levels.',
    sourceType: 'article',
    distillationStatus: 'distilled',
    bucketId: '4',
    bucketName: 'DeFi',
    bucketType: 'area',
    capturedAt: '2026-02-16',
    connectionCount: 8,
    sourceDomain: 'hyperliquid.xyz',
  },
  {
    id: 'n2',
    title: 'Funding Rate Arbitrage Between CEX and DEX',
    excerpt: 'The spread between Binance and Hyperliquid funding rates creates a persistent arb opportunity.',
    sourceType: 'tweet',
    distillationStatus: 'key_points',
    bucketId: '4',
    bucketName: 'DeFi',
    bucketType: 'area',
    capturedAt: '2026-02-15',
    connectionCount: 4,
    sourceDomain: 'x.com',
  },
  {
    id: 'n3',
    title: 'E30 M3 Engine Swap Options',
    excerpt: 'S50B32 is the most popular swap. Requires custom motor mounts and ECU remapping.',
    sourceType: 'article',
    distillationStatus: 'raw',
    bucketId: '5',
    bucketName: 'Cars',
    bucketType: 'area',
    capturedAt: '2026-02-14',
    connectionCount: 2,
    sourceDomain: 'bimmerforums.com',
  },
  {
    id: 'n4',
    title: 'Dieter Rams: Less But Better',
    excerpt: 'Good design is as little design as possible. Back to purity, back to simplicity.',
    sourceType: 'pdf',
    distillationStatus: 'evergreen',
    bucketId: '6',
    bucketName: 'Design',
    bucketType: 'area',
    capturedAt: '2025-11-20',
    connectionCount: 12,
  },
  {
    id: 'n5',
    title: 'On-chain Orderbook Tradeoffs',
    excerpt: 'Matching on-chain gives transparency but throughput is bottlenecked by block time.',
    sourceType: 'thought',
    distillationStatus: 'distilled',
    bucketId: '4',
    bucketName: 'DeFi',
    bucketType: 'area',
    capturedAt: '2026-02-13',
    connectionCount: 6,
  },
  {
    id: 'n6',
    title: 'Patek Philippe Nautilus History',
    excerpt: 'Designed by Gérald Genta in 1976. The porthole case shape was inspired by transatlantic ships.',
    sourceType: 'article',
    distillationStatus: 'key_points',
    bucketId: '8',
    bucketName: 'Watches',
    bucketType: 'area',
    capturedAt: '2026-02-08',
    connectionCount: 3,
    sourceDomain: 'hodinkee.com',
  },
]

export const inboxItems: InboxItem[] = [
  {
    id: 'i1',
    title: 'Thread: MEV on Hyperliquid L1',
    summary: 'Detailed analysis of how MEV extraction works on Hyperliquid\'s custom L1 vs Ethereum.',
    sourceType: 'tweet',
    suggestedBucket: 'Areas/DeFi',
    capturedAt: '2026-02-18',
  },
  {
    id: 'i2',
    title: 'Best Restaurants in Silver Lake',
    summary: 'Curated list of top-rated restaurants in the Silver Lake neighborhood of LA.',
    sourceType: 'article',
    suggestedBucket: 'Areas/LA',
    capturedAt: '2026-02-18',
  },
  {
    id: 'i3',
    title: 'Voice Memo: Idea for Order Routing',
    summary: 'Thought about smart order routing across multiple DEX venues based on depth.',
    sourceType: 'voice_memo',
    suggestedBucket: 'Projects/Perp Exchange Book',
    capturedAt: '2026-02-17',
  },
  {
    id: 'i4',
    title: 'A. Lange & Söhne Datograph Review',
    summary: 'Comprehensive review of the Datograph Up/Down. Considered one of the best chronographs ever made.',
    sourceType: 'article',
    suggestedBucket: 'Areas/Watches',
    capturedAt: '2026-02-17',
  },
  {
    id: 'i5',
    title: 'React Server Components Deep Dive',
    summary: 'Explains how RSC reduces client-side JS by rendering components on the server.',
    sourceType: 'article',
    suggestedBucket: 'Resources',
    capturedAt: '2026-02-16',
  },
]
