export type {
  ParaType,
  NoteSource,
  DistillationStatus,
  ConnectionType,
  SuggestionType,
  SuggestionStatus,
} from '@second-brain/shared'

export type {
  DashboardResponse,
  DashboardInboxItem,
  DashboardNote,
  DashboardArea,
  InboxResponse,
  UnifiedInboxItem,
  SuggestionItem,
  InboxItem,
  ClassifyRequest,
  BatchClassifyRequest,
  ParaTreeNode,
  ParaTreeResponse,
  BucketDetailResponse,
  BucketNote,
  CreateBucketRequest,
  UpdateBucketRequest,
  NoteDetailResponse,
  UpdateNoteRequest,
  ConnectNotesRequest,
  SearchRequest,
  SearchNotesResponse,
  SearchResult,
  SearchAnswerResponse,
  LinkCodeResponse,
  LinkStatusResponse,
  SuggestionsResponse,
} from '@second-brain/shared'
